import { Roboto, Marcellus } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Footer from "./subpages/Footer";
import ScrollToTop from "./subpages/ScrollToTop";
import { ToastContainer } from "react-toastify";
import queryClient from "./utils/ReactQueryClient";
import { StoreProvider } from "./context/StoreProvider";
import ReactQueryClient from "./utils/ReactQueryClient";

// Load fonts
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

const marcellus = Marcellus({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Wixad Hotels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` relative ${roboto.className} ${marcellus.className}`}>
        <StoreProvider>
          <ReactQueryClient>
            <ToastContainer />
            <Navbar />
            {children}
            <ScrollToTop />
            <Footer />
          </ReactQueryClient>
        </StoreProvider>
      </body>
    </html>
  );
}