import { Roboto, Marcellus } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Footer from "./subpages/Footer";
import ScrollToTop from "./subpages/ScrollToTop";

// Load fonts
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

const marcellus = Marcellus({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Job Hunt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` relative ${roboto.className} ${marcellus.className}`}>
        <Navbar />
        {children}
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}